### ISSUE TITLE
blobSpotter output image flashing

### ISSUE THREAD

**Issue by gsaponaro** [robotology/iol#14]
Hi @vtikha, just wanted to report that the segmented output image flashes because of the fact that ```cv::floodFill``` is sometimes filling open contours, therefore filling the whole image.

Not high priority for POETICON++, our visual pipeline still works, just a minor annoyance for visualization.

**Comment by vtikha** [comment]
@gsaponaro This happens as the point for the `cv::floodfill` is in the cog of the object. Depending on the objects you use and how they are made, the seed could be located outside of the object and therefore fill the whole image. As this is not a heavily used module, I will remove the floodfill so that you will not have any more annoying visualisation.

**Comment by gsaponaro** [comment]
Alright, thanks.
